export class Customer {
  id?: string;
  ID_number: string;
  ID_class: string;
  name: string;
  birthday: string;
  current_area_code: string;
  current_residence: string;
  phone_area_code: string;
  phone: string;
  phone_ext: string;
  mobile: string;
  payment: string;
  isMammoCar: string;
  mammoCar_number: string;
  affiliated_code: string;
  mammoCar_code: string;
  hx_number: string;
  education: string;
  height: string;
  weight: string;
  past_hx: string;
  cancer_hx: string;
  isBreastCa_family_hx: string;
  mother_number: string;
  sister_number: string;
  daughter_number: string;
  grandma_mother_number: string;
  grandma_father_number: string;
  menarche: string;
  isMenopause: string;
  menopause_period: string;
  menopause_causes: string;
  menopause_other: string;
  production_number: string;
  isBreastFeeding: string;
  production_age: string;
  isHormone: string;
  hormone_age: string;
  hormone_period: string;
  isContraceptive: string;
  contraceptive_age: string;
  contracepative_period: string;
  isSelfExam: string;
  isTouch: string;
  isMammo: string;
  isSono: string;
  isNoExam: string;
  isOP: string;
  OP_left: string;
  OP_right: string;
  hospital_code: string;
  mammo_day: string;
  mammo_machine: string;
  touch_result: string;
  gland_composition: string;
  isComparison: string;
  noOldMammo_cause: string;
  report_day: string;
  mammo_category: string;
  cat4_subtype: string;
  report_Dr: string;
  technician: string;
  referHospital_code: string;
  IsMass: string;
  mass_right: string;
  mass_left: string;
  mass_uni: string;
  mass_bil: string;
  mass_UOQ: string;
  mass_UIQ: string;
  mass_LOQ: string;
  mass_LIQ: string;
  mass_subareolar: string;
  mass_axilla: string;
  mass_oneView_upper: string;
  mass_oneView_lower: string;
  mass_oneView_outer: string;
  mass_oneView_inner: string;
  mass_size_1: string;
  mass_size_2: string;
  mass_size_3: string;
  mass_size_4: string;
  mass_size_large: string;
  mass_round: string;
  mass_ovale: string;
  mass_lobular: string;
  mass_irregular: string;
  mass_circum: string;
  mass_microlob: string;
  mass_obscured: string;
  mass_indistinct: string;
  mass_spiculated: string;
  mass_highDensity: string;
  mass_equalDensity: string;
  mass_lowDensity: string;
  mass_fat: string;
  isCal: string;
  cal_right: string;
  cal_left: string;
  cal_uni: string;
  cal_bil: string;
  cal_UOQ: string;
  cal_UIQ: string;
  cal_LOQ: string;
  cal_LIQ: string;
  cal_subareolar: string;
  cal_axilla: string;
  cal_oneView_upper: string;
  cal_oneView_lower: string;
  cal_oneView_outer: string;
  cal_oneView_inner: string;
  cal_grouped: string;
  cal_linear: string;
  cal_segmental: string;
  cal_regional: string;
  cal_diffuse: string;
  cal_amorphous: string;
  cal_coarseHetero: string;
  cal_finePleo: string;
  cal_fineBranching: string;
  isAsym: string;
  asym_right: string;
  asym_left: string;
  Asymmetry: string;
  focalAsymmetry: string;
  asym_developing: string;
  asym_UOQ: string;
  asym_UIQ: string;
  asym_LOQ: string;
  asym_LIQ: string;
  asym_subareolar: string;
  asym_axilla: string;
  asym_oneView_upper: string;
  asym_oneView_lower: string;
  asym_oneView_outer: string;
  asym_oneView_inner: string;
  isDistorsion: string;
  distorsion_right: string;
  distorsion_left: string;
  distorsion_UOQ: string;
  distorsion_UIQ: string;
  distorsion_LOQ: string;
  distorsion_LIQ: string;
  distorsion_subareolar: string;
  distorsion_axilla: string;
  distorsion_oneView_upper: string;
  distorsion_oneView_lower: string;
  distorsion_oneView_outer: string;
  distorsion_oneView_inner: string;
  isRectraction: string;
  retraction_right: string;
  retraction_left: string;
  isLN: string;
  LN_right: string;
  LN_left: string;
  isDuct: string;
  duct_right: string;
  duct_left: string;
  isSkin: string;
  skin_right: string;
  skin_left: string;
  isOther: string;
  Other: string;

  labels?: any;

  constructor(customer) {
    this.ID_number = customer.ID_number;
    this.ID_class = customer.ID_class;
    this.name = customer.name;
    this.birthday = customer.birthday;
    this.current_area_code = customer.current_area_code;
    this.current_residence = customer.current_residence;
    this.phone_area_code = customer.phone_area_code;
    this.phone = customer.phone;
    this.phone_ext = customer.phone_ext;
    this.mobile = customer.mobile;
    this.payment = customer.payment;
    this.isMammoCar = customer.isMammoCar;
    this.mammoCar_number = customer.mammoCar_number;
    this.affiliated_code = customer.affiliated_code;
    this.mammoCar_code = customer.mammoCar_code;
    this.hx_number = customer.hx_number;
    this.education = customer.education;
    this.height = customer.height;
    this.weight = customer.weight;
    this.past_hx = customer.past_hx;
    this.cancer_hx = customer.cancer_hx;
    this.isBreastCa_family_hx = customer.isBreastCa_family_hx;
    this.mother_number = customer.mother_number;
    this.sister_number = customer.sister_number;
    this.daughter_number = customer.daughter_number;
    this.grandma_mother_number = customer.grandma_mother_number;
    this.grandma_father_number = customer.grandma_father_number;
    this.menarche = customer.menarche;
    this.isMenopause = customer.isMenopause;
    this.menopause_period = customer.menopause_period;
    this.menopause_causes = customer.menopause_causes;
    this.menopause_other = customer.menopause_other;
    this.production_number = customer.production_number;
    this.isBreastFeeding = customer.isBreastFeeding;
    this.production_age = customer.production_age;
    this.isHormone = customer.isHormone;
    this.hormone_age = customer.hormone_age;
    this.hormone_period = customer.hormone_period;
    this.isContraceptive = customer.isContraceptive;
    this.contraceptive_age = customer.contraceptive_age;
    this.contracepative_period = customer.contracepative_period;
    this.isSelfExam = customer.isSelfExam;
    this.isTouch = customer.isTouch;
    this.isMammo = customer.isMammo;
    this.isSono = customer.isSono;
    this.isNoExam = customer.isNoExam;
    this.isOP = customer.isOP;
    this.OP_left = customer.OP_left;
    this.OP_right = customer.OP_right;
    this.hospital_code = customer.hospital_code;
    this.mammo_day = customer.mammo_day;
    this.mammo_machine = customer.mammo_machine;
    this.touch_result = customer.touch_result;
    this.gland_composition = customer.gland_composition;
    this.isComparison = customer.isComparison;
    this.noOldMammo_cause = customer.noOldMammo_cause;
    this.report_day = customer.report_day;
    this.mammo_category = customer.mammo_category;
    this.cat4_subtype = customer.cat4_subtype;
    this.report_Dr = customer.report_Dr;
    this.technician = customer.technician;
    this.referHospital_code = customer.referHospital_code;
    this.IsMass = customer.IsMass;
    this.mass_right = customer.mass_right;
    this.mass_left = customer.mass_left;
    this.mass_uni = customer.mass_uni;
    this.mass_bil = customer.mass_bil;
    this.mass_UOQ = customer.mass_UOQ;
    this.mass_UIQ = customer.mass_UIQ;
    this.mass_LOQ = customer.mass_LOQ;
    this.mass_LIQ = customer.mass_LIQ;
    this.mass_subareolar = customer.mass_subareolar;
    this.mass_axilla = customer.mass_axilla;
    this.mass_oneView_upper = customer.mass_oneView_upper;
    this.mass_oneView_lower = customer.mass_oneView_lower;
    this.mass_oneView_outer = customer.mass_oneView_outer;
    this.mass_oneView_inner = customer.mass_oneView_inner;
    this.mass_size_1 = customer.mass_size_1;
    this.mass_size_2 = customer.mass_size_2;
    this.mass_size_3 = customer.mass_size_3;
    this.mass_size_4 = customer.mass_size_4;
    this.mass_size_large = customer.mass_size_large;
    this.mass_round = customer.mass_round;
    this.mass_ovale = customer.mass_ovale;
    this.mass_lobular = customer.mass_lobular;
    this.mass_irregular = customer.mass_irregular;
    this.mass_circum = customer.mass_circum;
    this.mass_microlob = customer.mass_microlob;
    this.mass_obscured = customer.mass_obscured;
    this.mass_indistinct = customer.mass_indistinct;
    this.mass_spiculated = customer.mass_spiculated;
    this.mass_highDensity = customer.mass_highDensity;
    this.mass_equalDensity = customer.mass_equalDensity;
    this.mass_lowDensity = customer.mass_lowDensity;
    this.mass_fat = customer.mass_fat;
    this.isCal = customer.isCal;
    this.cal_right = customer.cal_right;
    this.cal_left = customer.cal_left;
    this.cal_uni = customer.cal_uni;
    this.cal_bil = customer.cal_bil;
    this.cal_UOQ = customer.cal_UOQ;
    this.cal_UIQ = customer.cal_UIQ;
    this.cal_LOQ = customer.cal_LOQ;
    this.cal_LIQ = customer.cal_LIQ;
    this.cal_subareolar = customer.cal_subareolar;
    this.cal_axilla = customer.cal_axilla;
    this.cal_oneView_upper = customer.cal_oneView_upper;
    this.cal_oneView_lower = customer.cal_oneView_lower;
    this.cal_oneView_outer = customer.cal_oneView_outer;
    this.cal_oneView_inner = customer.cal_oneView_inner;
    this.cal_grouped = customer.cal_grouped;
    this.cal_linear = customer.cal_linear;
    this.cal_segmental = customer.cal_segmental;
    this.cal_regional = customer.cal_regional;
    this.cal_diffuse = customer.cal_diffuse;
    this.cal_amorphous = customer.cal_amorphous;
    this.cal_coarseHetero = customer.cal_coarseHetero;
    this.cal_finePleo = customer.cal_finePleo;
    this.cal_fineBranching = customer.cal_fineBranching;
    this.isAsym = customer.isAsym;
    this.asym_right = customer.asym_right;
    this.asym_left = customer.asym_left;
    this.Asymmetry = customer.Asymmetry;
    this.focalAsymmetry = customer.focalAsymmetry;
    this.asym_developing = customer.asym_developing;
    this.asym_UOQ = customer.asym_UOQ;
    this.asym_UIQ = customer.asym_UIQ;
    this.asym_LOQ = customer.asym_LOQ;
    this.asym_LIQ = customer.asym_LIQ;
    this.asym_subareolar = customer.asym_subareolar;
    this.asym_axilla = customer.asym_axilla;
    this.asym_oneView_upper = customer.asym_oneView_upper;
    this.asym_oneView_lower = customer.asym_oneView_lower;
    this.asym_oneView_outer = customer.asym_oneView_outer;
    this.asym_oneView_inner = customer.asym_oneView_inner;
    this.isDistorsion = customer.isDistorsion;
    this.distorsion_right = customer.distorsion_right;
    this.distorsion_left = customer.distorsion_left;
    this.distorsion_UOQ = customer.distorsion_UOQ;
    this.distorsion_UIQ = customer.distorsion_UIQ;
    this.distorsion_LOQ = customer.distorsion_LOQ;
    this.distorsion_LIQ = customer.distorsion_LIQ;
    this.distorsion_subareolar = customer.distorsion_subareolar;
    this.distorsion_axilla = customer.distorsion_axilla;
    this.distorsion_oneView_upper = customer.distorsion_oneView_upper;
    this.distorsion_oneView_lower = customer.distorsion_oneView_lower;
    this.distorsion_oneView_outer = customer.distorsion_oneView_outer;
    this.distorsion_oneView_inner = customer.distorsion_oneView_inner;
    this.isRectraction = customer.isRectraction;
    this.retraction_right = customer.retraction_right;
    this.retraction_left = customer.retraction_left;
    this.isLN = customer.isLN;
    this.LN_right = customer.LN_right;
    this.LN_left = customer.LN_left;
    this.isDuct = customer.isDuct;
    this.duct_right = customer.duct_right;
    this.duct_left = customer.duct_left;
    this.isSkin = customer.isSkin;
    this.skin_right = customer.skin_right;
    this.skin_left = customer.skin_left;
    this.isOther = customer.isOther;
    this.Other = customer.Other;
    this.labels = customer.labels;
  }

  get city() {
    return `${this.current_residence.substring(0, 3)}`;
  }

  set city(value) {}

  get area_code() {
    return `${this.current_residence.substring(3, 6)}`;
  }

  set area_code(value) {}
}
